name: Build MemFilterApp EFI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Clone edk2
        run: |
          git clone https://github.com/tianocore/edk2.git edk2 --depth=1
          cd edk2
          git submodule update --init MdePkg
          cd ..
          mkdir -p edk2/MyMemCheckPkg/MemFilterApp
          cp MemFilterApp.c edk2/MyMemCheckPkg/MemFilterApp/
          cp MemFilterApp.inf edk2/MyMemCheckPkg/MemFilterApp/
          cp MyMemCheckPkg.dsc edk2/MyMemCheckPkg/
          cp MyMemCheckPkg.dec edk2/MyMemCheckPkg/
      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc nasm iasl python3
      - name: Compile EDK2
        run: |
          cd edk2
          export PACKAGES_PATH=$PWD
          make -C BaseTools
          source edksetup.sh
          build -a X64 -t GCC5 -p MyMemCheckPkg/MyMemCheckPkg.dsc
      - name: Upload efi artifact
        uses: actions/upload-artifact@v4
        with:
          name: MemFilterAppEFI
          path: edk2/Build/MyMemCheckPkg/DEBUG_GCC5/X64/MemFilterApp.efi
