name: Build MemFilterApp EFI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu‑latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Pull edk2 source
        run: |
          git clone https://github.com/tianocore/edk2.git edk2 --depth=1
          cd edk2
          git submodule update --init MdePkg

      - name: Copy our whole package into edk2
        run: cp -r ./MyMemCheckPkg ./edk2/

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc nasm iasl python3

      - name: Compile BaseTools
        run: |
          cd edk2
          make -C BaseTools

      - name: Build UEFI App
        run: |
          cd edk2
          export PACKAGES_PATH="$PWD"
          source edksetup.sh
          build -a X64 -t GCC5 -p MyMemCheckPkg/MyMemCheckPkg.dsc

      - name: Download artifact
        uses: actions/upload-artifact@v4
        with:
          name: MemFilterAppEFI
          path: edk2/Build/MyMemCheckPkg/DEBUG_GCC5/X64/MemFilterApp.efi
